#!/usr/bin/env bash

if [ -z "$(which zola)" ]; then
    echo "zola not found, please install it first"
    exit 1
fi

function gen_weekly() {
    title=${1-"周报"}
    lang=${2-"zh"}
    week=$(date +"%Y-%U")
    if [ "${lang}" == "en" ]; then
        file="content/weekly/${week}.md"
    else
        file="content/weekly/${week}.${lang}.md"
    fi
    if [ -e "${file}" ]; then
        echo "Weekly report exist, skip"
        exit 0
    fi
    echo "---
title: ${week} ${title}
date: $(date +"%Y-%m-%d")
---" >> $file
    echo "Weekly report generated in '${file}'"
}

function code_gdb() {
    set -eux;
    path=${1}
    output="./.debug/a-gdb-${RANDOM}.out"
    g++ -g $path -o $output
    gdb $output
    rm $output
}

function leetcode() {
    if [ -z "$(which leetui)" ]; then
        echo "leetui not found, please use <cargo install leetcode-tui-rs> and try it later"
        exit 1
    fi
    path=${1-'./code/leetcode'}
    if [ ! -d $path ]; then
        mkdir -p $path
        sed -i -E "s#solutions_dir = \"(.+)\"#solutions_dir = \"$path\"#" $HOME/.config/leetui/config.toml
    fi
    leetui
}

function main() {
    cmd=$1
    shift
    case $cmd in
        "gen_weekly" | "gw")
            gen_weekly $@
        ;;
        "view" | "v")
            zola serve
        ;;
        "gdb")
            code_gdb $@
        ;;
        "lc")
            leetcode $@
        ;;
        *)
            echo "Commands:
    gen_weekly, gw [title] [lang]  Generate weekly report
    view, v                        View the blog
    gdb [path]                     Debug C/C++ source file"
            exit 1
        ;;
    esac
}

main $@
