base_url = "https://blog.skygard.work"
author = "iGxnon"
default_language = "en"
theme = "no-style-please"

[languages.en]
title = "iGxnon's blog"
description = "iGxnon's blog, writing feelings"
taxonomies = [{ name = "tags" }, { name = "categories" }]

[languages.zh]
title = "泡泡的空中花园"
description = "我所想往的，无非是依靠着我本性而生活"
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
render_emoji = true

[extra]
logo = "images/logo.png"
header_nav = [
    { lang = "en", name = "about", path = "/about" },
    { lang = "zh", name = "关于", path = "/zh/about" },

    { lang = "en", name = "archived", path = "/posts" },
    { lang = "zh", name = "归档", path = "/zh/posts" },

    { lang = "en", name = "friends", path = "/friends" },
    { lang = "zh", name = "朋友", path = "/zh/friends" },

    { lang = "en", name = "RSS", url = "/posts/atom.xml" },
    { lang = "zh", name = "订阅", url = "/zh/posts/atom.xml" },

    { lang = "en", name = "*简中", path = "/zh" },
    { lang = "zh", name = "*English", path = "/" },
]
recent_pages = [
    { lang = "en", section = "posts/_index.md", limit = 7 },
    { lang = "zh", section = "posts/_index.zh.md", limit = 7 },
]
taxonomies_map = [
    { lang = "zh", taxonomy = "tags", name = "标签" },
    { lang = "zh", taxonomy = "categories", name = "分类" },
]
paginator_hint.first = [
    { lang = "zh", hint = "开头" },
    { lang = "en", hint = "First" },
]
paginator_hint.previous = [
    { lang = "zh", hint = "前一页" },
    { lang = "en", hint = "Pervious" },
]
paginator_hint.next = [
    { lang = "zh", hint = "下一页" },
    { lang = "en", hint = "Next" },
]
paginator_hint.last = [
    { lang = "zh", hint = "结尾" },
    { lang = "en", hint = "Last" },
]

[extra.giscus]
enable = true
data_repo = "iGxnon/blog"
data_repo_id = "R_kgDOJdd9lw"
data_category = "Announcements"
data_category_id = "DIC_kwDOJdd9l84CbO42"
lang_map = [{ lang = "zh", to = "zh-CN" }]
